name 'SQLServer'
maintainer 'Ray Terrill'
maintainer_email 'dontemailme@null.com'
license 'all_rights'
description 'Installs/Configures SQLServer'
long_description 'Installs/Configures SQLServer'
version '0.1.12'
